# Generated by Django 5.2.5 on 2025-08-19 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('imageUrl', models.CharField(max_length=64)),
                ('countryOfOrigin', models.CharField(max_length=64)),
                ('typicalMealTime', models.IntegerField(choices=[(1, 'morning'), (2, 'afternoon'), (3, 'evening')])),
                ('dateAdded', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MealRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('dateOfRating', models.DateTimeField()),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='mealRatings.meal')),
            ],
        ),
    ]
